package com.aed.kanbanpro.view;

import com.aed.kanbanpro.controller.KanbanProController;
import com.aed.kanbanpro.util.PropertyTable;
import com.formdev.flatlaf.IntelliJTheme;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.JTable;

/**
 *
 * @author Juan Romero Collazos
 */
public class KanbanPro extends javax.swing.JFrame {
    private static final Logger LOGGER = Logger.getLogger(KanbanPro.class.getName());
    private final PropertyTable PROPERTY_TABLE;
    private final KanbanProController CONTROLLER;
    private final PanelAddTask PANEL_ADD_TASK;
    private final PanelConfigTask PANEL_CONFIG_TASK;
    /**
     * Creates new form KanbanPro
     */
    public KanbanPro() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        // Initialize the panels
        PANEL_ADD_TASK = new PanelAddTask();
        PANEL_CONFIG_TASK = new PanelConfigTask();
        
        // Initialize the controller
        CONTROLLER = new KanbanProController(this, PANEL_ADD_TASK, PANEL_CONFIG_TASK);
        setIconImage(new ImageIcon(getClass().getResource("/img/favicon.png")).getImage());
        PROPERTY_TABLE = new PropertyTable();
        String[] columns = {"CATÁLOGO", "POR HACER", "EN PROGRESO", "POR VERIFICAR", "HECHO"};
        PROPERTY_TABLE.insertHeaders(table, columns);
        PROPERTY_TABLE.tableHeaderColor(table, "#156082", "#007d38", "#008abd", "#c00000", "#997200");
        table.setEnabled(false);
    }

    public JMenu getBtn_add() {
        return btn_add;
    }

    public JMenu getBtn_export() {
        return btn_export;
    }

    public JMenu getBtn_import() {
        return btn_import;
    }

    public JTable getTable() {
        return table;
    }

    public JMenu getBtn_redo() {
        return btn_redo;
    }

    public JMenu getBtn_undo() {
        return btn_undo;
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        navbar = new javax.swing.JMenuBar();
        btn_add = new javax.swing.JMenu();
        btn_import = new javax.swing.JMenu();
        btn_export = new javax.swing.JMenu();
        btn_undo = new javax.swing.JMenu();
        btn_redo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kanban Pro | Home");
        setPreferredSize(new java.awt.Dimension(800, 400));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        contentTable.setViewportView(table);

        getContentPane().add(contentTable, java.awt.BorderLayout.CENTER);

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navbar.add(btn_add);

        btn_import.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/importar.png"))); // NOI18N
        btn_import.setText("Import");
        btn_import.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_import.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navbar.add(btn_import);

        btn_export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exportar.png"))); // NOI18N
        btn_export.setText("Export");
        btn_export.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_export.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navbar.add(btn_export);

        btn_undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deshacer.png"))); // NOI18N
        btn_undo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_undo.setEnabled(false);
        navbar.add(btn_undo);

        btn_redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rehacer.png"))); // NOI18N
        btn_redo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_redo.setEnabled(false);
        navbar.add(btn_redo);

        setJMenuBar(navbar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            IntelliJTheme.setup(KanbanPro.class.getResourceAsStream("/theme/cyberpunk_theme.theme.json"));
            System.setProperty("flatlaf.menuBarEmbedded", "true");
            System.setProperty("flatlaf.useWindowDecorations", "true");
            System.setProperty("flatlaf.animation", "true");
            System.setProperty("flatlaf.useTextYCorrection", "true");
        } catch (Exception e) {
            LOGGER.info(String.format("Mensaje de información: %s", e.getMessage()));
            LOGGER.warning(String.format("Mensaje de advertencia: %s", e.getMessage()));
            LOGGER.severe(String.format("Mensaje de error: %s", e.getMessage()));
        }
        java.awt.EventQueue.invokeLater(() -> {
            new KanbanPro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btn_add;
    private javax.swing.JMenu btn_export;
    private javax.swing.JMenu btn_import;
    private javax.swing.JMenu btn_redo;
    private javax.swing.JMenu btn_undo;
    private javax.swing.JScrollPane contentTable;
    private javax.swing.JMenuBar navbar;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
