package com.aed.kanbanpro.view;

import com.aed.kanbanpro.util.PropertySpinner;
import com.aed.kanbanpro.util.PropertyTextArea;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Juan Romero Collazos
 */
public class PanelAddTask extends javax.swing.JFrame {
    private final PropertyTextArea PROPERTY_TEXT_AREA;
    private final PropertySpinner PROPERTY_SPINNER;
    /**
     * Creates new form PanelAddTask
     */
    public PanelAddTask() {
        initComponents();
        PROPERTY_TEXT_AREA = new PropertyTextArea();
        PROPERTY_SPINNER = new PropertySpinner();
        setIconImage(new ImageIcon(getClass().getResource("/img/favicon.png")).getImage());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        input_name.putClientProperty( "JComponent.roundRect", true );
        input_name.putClientProperty( "JTextField.placeholderText", "Escribe tus nombres..." );
        input_lastname.putClientProperty( "JComponent.roundRect", true );
        input_lastname.putClientProperty( "JTextField.placeholderText", "Escribe tus apellidos..." );
        sp_priority.putClientProperty( "JComponent.roundRect", true );
        length_words.setHorizontalAlignment(SwingConstants.RIGHT);
        btn_add.putClientProperty( "JButton.buttonType", "roundRect" );
        PROPERTY_TEXT_AREA.limitTextArea(100, txt_description, length_words);
        PROPERTY_SPINNER.property(sp_priority, 1, 1, 5, 1);
    }

    public JButton getBtn_add() {
        return btn_add;
    }

    public JTextField getInput_lastname() {
        return input_lastname;
    }

    public JTextField getInput_name() {
        return input_name;
    }

    public JLabel getLabel_description() {
        return label_description;
    }

    public JSpinner getSp_priority() {
        return sp_priority;
    }

    public JTextArea getTxt_description() {
        return txt_description;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_name = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        label_lastname = new javax.swing.JLabel();
        input_lastname = new javax.swing.JTextField();
        label_priority = new javax.swing.JLabel();
        sp_priority = new javax.swing.JSpinner();
        label_description = new javax.swing.JLabel();
        content_text_description = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        length_words = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kanban Pro | Add");
        setMinimumSize(new java.awt.Dimension(510, 500));
        setResizable(false);

        label_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_name.setForeground(new java.awt.Color(31, 137, 201));
        label_name.setText("Nombres:");

        label_lastname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_lastname.setForeground(new java.awt.Color(31, 137, 201));
        label_lastname.setText("Apellidos:");

        label_priority.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_priority.setForeground(new java.awt.Color(31, 137, 201));
        label_priority.setText("Prioridad:");

        label_description.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_description.setForeground(new java.awt.Color(31, 137, 201));
        label_description.setText("Descripción:");

        txt_description.setColumns(20);
        txt_description.setLineWrap(true);
        txt_description.setRows(5);
        txt_description.setWrapStyleWord(true);
        content_text_description.setViewportView(txt_description);

        length_words.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        length_words.setForeground(new java.awt.Color(255, 212, 0));
        length_words.setText("0/100");

        btn_add.setBackground(new java.awt.Color(31, 137, 201));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btn_add.setText("Agregar");
        btn_add.setBorderPainted(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(length_words, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_description, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_lastname)
                        .addGap(18, 18, 18)
                        .addComponent(input_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_name)
                        .addGap(18, 18, 18)
                        .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_priority)
                        .addGap(18, 18, 18)
                        .addComponent(sp_priority))
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content_text_description, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_priority)
                    .addComponent(sp_priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lastname)
                    .addComponent(input_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_description)
                .addGap(18, 18, 18)
                .addComponent(content_text_description, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(length_words)
                .addGap(18, 18, 18)
                .addComponent(btn_add)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JScrollPane content_text_description;
    private javax.swing.JTextField input_lastname;
    private javax.swing.JTextField input_name;
    private javax.swing.JLabel label_description;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_priority;
    private javax.swing.JLabel length_words;
    private javax.swing.JSpinner sp_priority;
    private javax.swing.JTextArea txt_description;
    // End of variables declaration//GEN-END:variables
}
